#if !canImport(ObjectiveC)
  import XCTest

  extension AckeeTrackerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AckeeTrackerTests = [
      ("testPerformsRequest", testPerformsRequest)
    ]
  }

  public func __allTests() -> [XCTestCaseEntry] {
    return [
      testCase(AckeeTrackerTests.__allTests__AckeeTrackerTests)
    ]
  }
#endif
